# How to work with Visual Studio Code

## AI (GitHub Copilot)

- Turn off GitHub Copilot for now; we'll use it in part two (`File` → `Preferences` → `Settings`, search for `Chat: Disable AI Features`)

## Interacting with Git

- Use the **Source control** tab to directly interact with `git` within VS Code
- The upper part of the panel displays changes you made, indicated with various icons:
    - <span style="color: green; font-weight: bold;">U</span> = Untracked (new file)
    - <span style="color: green; font-weight: bold;">A</span> = Added
    - <span style="color: orange; font-weight: bold;">M</span> = Modified
    - <span style="color: red; font-weight: bold;">D</span> = Deleted
- The lower part of the panel shows you the entire commit history

**Getting updates from GitHub**
- To get new commits from GitHub, click the `...` menu and select `Pull`
- **Important**: `Pull` may fail if you have uncommitted changes (files marked with <span style="color: green; font-weight: bold;">A</span>, <span style="color: orange; font-weight: bold;">M</span>, <span style="color: red; font-weight: bold;">D</span>).



**Important**: 
- Never edit files in the git repository directly, as this will potentially create conflicts.
- Instead, always create your own version, e.g., copy `lecture01.ipynb` to `lecture01_yourname.ipynb` and edit that file.


## Jupyter notebooks in VS Code

### Inserting new cells

- Insert a new cell above (`a`) or below (`b`)
- Clicking `+ Code` or `+ Markdown` from the toolbar inserts a code or markdown cell *below*
- Switching between Markdown (text) and Code cell modes: `y` for Code, `m` for Markdown

### Running code

- Before running code, select the desired kernel: `Select Kernel` → `Python Environments` → `FIE463`
- Execute a code cell with `Ctrl` + `Return`
- Execute all cells with `Run All` from the notebook toolbar
- Restart the Jupyter kernel with `Restart` (useful if nothing works when it should)

***
# Python: Language and NumPy basics

***
## Basic syntax

-   Everything after a `#` character (until the end of the line) is a **comment** and will be ignored.
-   Variables are created using the assignment operator `=`.
-   Whitespace characters matter (unlike in most languages)!
-   Python uses indentation (usually 4 spaces) to group statements,
    for example loop bodies, functions, etc.
-   You can use the `print()` function to inspect almost any object.

In [5]:
# This is a comment
text = 'Hello World!'
print(text)

Hello World!


In [7]:
text1 = 'Hello, '
text2 = 'world!'

print(text1)
print(text2)

Hello, 
world!


### Variable names

**Valid variable names**

- Must start with a letter (A–Z, a–z) or underscore `_` (e.g., `a`, `_count`, `arr2`)
- Remaining characters can be letters, digits or underscores
- Are case-sensitive (`var` != `Var`)
- Cannot be a Python keyword (words with special meaning which we encounter later)

**Invalid variable names**

- Start with a digit (e.g., `1var`)
- Contain spaces or punctuation (e.g., `my var`, `my-var`)
- Are Python keywords (e.g., `def`, `class`, `True`, `None`)
- Contain operator characters or other symbols (e.g., `a+b`, `x%`)

***
## Built-in data types

Python is a dynamically-typed language:

-   No need to declare a variable or its type
-   You can inspect a variable's type using the built-in `type()` function (but this is rarely used)

**Basic types**

- integers (`int`)
- floating-point numbers (`float`)
- boolean (`bool`)
- strings (`str`)

**Containers (or collections)**

- tuples (`tuple`)
- lists (`list`)
- dictionaries (`dict`)

***
### Numerical data types

#### Integers and floats

- **Integers:** created from literal values *without* decimal dot
- **Floats:** created from literal values *with* decimal dot or scientific notation (e.g., $5 \times 10^{-8}$ is written as `5e-8`)
- Optional _ as thousands separator

#### Booleans

- Created using the keywords `True` and `False`

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>
Floating-point numbers cannot represent real numbers with arbitrary precision. This can lead to surprising results:
<ol>
    <li>Define the floating-point number <tt>x</tt> with value <tt>1/3</tt>.</li>
    <li>Add <tt>x</tt> three times (<tt>x + x + x</tt>) and print the result.</li>
    <li>Add <tt>x</tt> six times and print the result.</li>
    <li>Rewrite the above expression as <tt>(x + x + x) + (x + x + x)</tt> and print the result.</li>
    <li>Add the floating-point numbers <i>1.0</i> and <i>10<sup>-15</sup></i> and print the result.
    What happens if you add <i>1.0</i> and <i>10<sup>-16</sup></i> instead?</li>
</ol>
</div>
<span style="display: none;">YourTurnEnd</span>

In [12]:
x = 1/3
print(x + x + x)
print(x + x + x + x + x + x)  # x * 6 does NOT yield this problem
print((x + x + x) + (x + x + x))
print(1.0 + 1.0e-15)
print(1.0 + 1.0e-16)

# Computer has a cutoff at 16 decimals (?)

1.0
1.9999999999999998
2.0
1.000000000000001
1.0


***
### Strings

- The string (`str`) data type is used to store text
- Enclosed in either `'` or `"`

#### String operations

- Can be concatenated with `+`
- Can be duplicated with `*`

In [15]:
s1 = 'NHH'
s2 = 'Norwegian School of Economics'

s1 + ' ' + s2

'NHH Norwegian School of Economics'

#### Formatting with f-strings

In [ ]:
pi = 3.1415
'Pi is approximately ' + str(pi)  

f"Pi is approximately {pi: .2f}"

'Pi is approximately 3.14'

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>
Continuing our experiments with floating-point numbers, perform the following tasks:
<ol>
    <li>Define the floating-point number <tt>x</tt> with value <tt>1/3</tt>, 
        and use an f-string to print it with 20 decimal digits.</li>
    <li>Define the floating-point number <tt>x</tt> with value <tt>0.1</tt>, 
        and use an f-string to print it with 20 decimal digits.</li>
</ol>

As you can see, problems not only arise if a real number has infinitely many 
decimal digits (like 1/3), but also if it cannot be exactly represented as a binary number (base-2).
</div>
<span style="display: none;">YourTurnEnd</span>

In [ ]:
x = 1/3
print(f"20 decimals of x: {x:.20f}")

x = 0.1
print(f"20 decimals of x: {x:.20f}")

# These issues are based on base-10 vs base-2 systems, read more on this

20 decimals of x: 0.33333333333333331483
20 decimals of x: 0.10000000000000000555


***
### Tuples

- *ordered, immutable collection* of items which can
have different data types
- Created using `,`
- Optionally enclosed in `()`
- Elements are accessed using `[]`
- Index is 0-based
- Built-in `len()` function returns number of items

In [29]:
items = 'NHH', 1, 1.0  # Using parenthesis is equivalent

# Retrieve elements with indexing (Starts at zero)
items[0]
items[2]  # Last element, when we know number of elements
items[-1]  # Last element, unknown length

# Define a tuple with a single element requires a comma after it:
items = (1, )

# Tuples are immutable (cannot be changed), lists are mutable
# items[0] = 'NHH'  # This doesn't work


***
### Lists

- Like tuples, but can be modified (*mutable*)
- Can use methods to modify lists: `append()`, `insert()`, `pop()` etc. (see [here](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists) for a complete list)

In [35]:
# Define a list (square brackets)
items = ['NHH', 1, 1.0]
items

# Lists are mutable
items[0] = 'Norwegian School of Economics'
items

# Append adds element at the end of the list
items.append('Python')
items

# Insert adds element to list at desired index
items.insert(1, 'NHH')
items

['Norwegian School of Economics', 'NHH', 1, 1.0, 'Python']

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>
Perform the following tasks to practice working with lists:
<ol>
    <li>Define a tuple containing a single value <tt>'a'</tt>.</li>
    <li>Convert the tuple to a list using the <a href="https://www.w3schools.com/python/ref_func_list.asp"><tt>list()</tt></a> function.</li>
    <li>Append the items <tt>'b'</tt> and <tt>'c'</tt> using the <a href="https://www.w3schools.com/python/ref_list_append.asp"><tt>append()</tt></a> method.</li>
    <li>Select the last element of the list. Determine the index of this last element using 
    the <tt>len()</tt> function.</li>
</ol>
</div>
<span style="display: none;">YourTurnEnd</span>

In [41]:
t = ('a', )
lst = list(t)
lst.append('b')
lst.append('c')
print(lst[-1])
print(len(lst))

# Alternatives to add 'b' and 'c' in a single line: extend and shorter syntax of extend
t2 = ('a', )
lst2 = list(t2)
lst2.extend(['b', 'c'])
# lst2 += (['b', 'c'])  # Don't use both, you will add elements twice, resulting in length 5, not 3
print(lst2[-1])
print(len(lst2))

c
3
c
3


***
### Dictionaries

- Map keys to values (keys don't have to be integers, unlike tuples, lists, etc.)
- Can be created using `{key: value}` syntax
- Alternatively created using `dict()`
- Elements are accessed using `[key]` 
- Methods `.keys()` and `.values()` return keys and values in dictionary

In [ ]:
currencies = {'EUR': 11.50, 'USD': 9.60, 'GBP': 13.50}
# currencies = dict()
currencies['EUR']

# See all keys or all values
currencies.keys()
currencies.values()

# Update a value
currencies['EUR'] = 12.0
currencies['EUR']

# Add a new key with value
currencies['SEK'] = 0.9
currencies['SEK']

dict_values([11.5, 9.6, 13.5])


0.9

***
## NumPy arrays


-   Data type to efficiently store numeric data
-   NumPy is *not* part of the core Python project
-   Must be imported prior to use: `import numpy as np`

In [ ]:
import numpy as np

### Creating arrays

#### Creating arrays from other Python objects

- Can be created from other sequence objects such as tuples or lists using [`np.array()`](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

In [59]:
# List of integers
lst = [1, 2, 3]

# Create a numpy array
arr = np.array(lst)

# They look only slightly different, but work very differently
print(lst)
print(arr)

# Multiply all elements by 2
print(lst * 2)  # only duplicates the list, not useful for us
print(arr * 2)  # multiplies each element by 2

# Add 1 to each element
# print(lst + 1)  # This doesn't work at all, can't add list and integer
print(arr + 1)

[1, 2, 3]
[1 2 3]
[1, 2, 3, 1, 2, 3]
[2 4 6]
[2 3 4]


#### Array creation routines

Functions to create arrays from scratch:

-   [`np.zeros()`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) 
    creates an array of a given shape and initializes it
    to zeros.
-   [`np.ones()`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html) 
    creates an array of a given shape and initializes it
    to ones.
-   [`np.arange(start,stop,step)`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) 
    creates an array with evenly spaced
    elements over the range $[start,stop)$.
    -   `start` and `step` can be omitted and then default to `start=0` and `step=1`.
    -   Note that the number `stop` is never included in
        the resulting array!
-   [`np.linspace(start,stop,num)`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) 
    returns a vector of `num` elements
    which are evenly spaced over the interval $[start,stop]$.

There are many more array creation functions for more exotic use-cases,
see the NumPy  [documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html)
for details.

In [ ]:
# Array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [65]:
# Matrix of ones
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Create sequence 0, 1, 2, 3, 4. Two equivalent methods, (first shows how it works)
# Starts at 0, contains 5 elements, and moves in steps of 1
np.arange(0, 5, 1)
# Assign only number of elements, default is starting at 0 with steps of 1
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
# Steps of 2
np.arange(0, 5, 2)

array([0, 2, 4])

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>
Lists and NumPy arrays behave differently in potentially unexpected ways. 
Perform the following tasks and inspect the result for both list and array arguments.
<ol>
    <li>Create two variables, a list and a NumPy array, both containing the elements <tt>[1, 2, 3]</tt>.</li>
    <li>Multiply the list and the array by 2.</li>
    <li>Add <tt>[4]</tt> to both the list and the array.</li>
    <li>Add <tt>4</tt> to both the list and the array. Does this work?</li>
</ol>
</div>
<span style="display: none;">YourTurnEnd</span>

In [78]:
# 1
lst = [1, 2, 3]
arr = np.arange(1, 4, 1)

print(lst)
print(arr)

# 2
lst2 = lst * 2
arr2 = arr * 2

print(lst2)
print(arr2)

# 3
lst.append(4)
arr = np.append(arr, 4)

print(lst)
print(arr)

# 4
# lst4 = lst + 4  # not possible
arr4 = arr + 4

# print(lst4)
print(arr4)

[1, 2, 3]
[1 2 3]
[1, 2, 3, 1, 2, 3]
[2 4 6]
[1, 2, 3, 4]
[1 2 3 4]
[5 6 7 8]


### Reshaping arrays

- The `reshape()` method reshapes array to some other (conformable) shape
- Can be used to create lower- or higher-dimensional arrays
- One dimension in shape can be omitted using `-1`

***
### Indexing

#### Single element indexing

-   NumPy arrays use 0-based indices
-   Unlike lists or tuples, NumPy arrays support multi-dimensional
    indexing
-   Use `arr[i, j]`, *not* `arr[i][j]`

#### Index slices

- Slicing with `start:stop:step` syntax retrieves ranges of elements.

*Rules:*

-   all tokens in `start:stop:step` are optional, with
    the obvious default values.
    We could therefore write `::` to include all indices,
    which is the same as `:`
- The end value is *not* included. Writing
  `vec[0:n]` does not include element with index $n$!
- Any of the elements of `start:stop:step` can be negative.
    - If `start` or `stop` are negative, elements are counted
        from the end of the array:
        `vec[:-1]` retrieves the whole vector except for the last element.
    - If `step` is negative, the order of elements is reversed.

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>
Perform the following tasks to practice working with NumPy arrays:
<ol>
    <li>Create a NumPy array containing the sequence from 5 to 100 (inclusive).</li>
    <li>Select and print every 5th element from the array.</li>
    <li>Select the last element in two different ways without hardcoding the index.
    <br/><i>Hint:</i> The function <tt>len()</tt> also works for NumPy arrays.</li>
</ol>
</div>
<span style="display: none;">YourTurnEnd</span>

In [87]:
# 1
arr = np.arange(5, 101, 1)

# 2
print(arr[::5])

# 3
print(arr[len(arr) - 1])  # 0-based indices, subtract one from length to find last element
print(arr[-1])


[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]
100
100


***
### Numerical data types (advanced)

- Most array creation routines support `dtype` argument to specify data type
- Valid values: `int`, `float`, `np.float64`, `np.float32`, `np.int64`, `np.int32`, ...
- Use data type that is appropriate for the task!