
<style>
.ui-button {
color: #363636; background-color: #CCCCCC; font-weight: normal; border: 1pt solid #363636; 
padding: 0.2em 0.3em; 
}
</style>
<div style="background-color: #feb24c; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Reminder: Turn off built-in AI (GitHub Copilot) for now</h3> 

<ul>
    <li>
    <p>
    <b>Windows/Linux:</b> Go to
        <span class="ui-button">File</span> 🡆
        <span class="ui-button">Preferences</span> 🡆
        <span class="ui-button">Settings</span> and search for 
        <span class="ui-button">Chat: Disable AI Features</span>
        and remove the 🗹
    </p>
    </li>
    <li>
    <p>
    <b>macOS:</b> Go to
        <span class="ui-button">Code</span> 🡆
        <span class="ui-button">Settings</span> 🡆
        <span class="ui-button">Settings</span> and search for 
        <span class="ui-button">Chat: Disable AI Features</span>
        and remove the 🗹
    </p>
    </li>
</ul>
</div>

***
# Last week: Functions and modules

## Functions

-   Allow for code reuse
-   Allow for robust code:

    -   Local scope
    -   Clear interface via arguments & return values
-   Various argument types: 

    ```python
    def func(x, opt='default', *args, **kwargs):
        pass
    ```
-   `lambda` expressions: short-hand syntax to declare functions

## Modules

-   Every Python file (`*.py`) or Jupyter notebook (`*.ipynb`) constitutes a module
-   Modules bundle related code within one scope
-   Need to be imported before use:

    ```python
    import mymodule
    import mymodule as mm
    from mymodule import myfunction
    from mymodule import myfunction as f
    ```

***
# Random number generation

## Random number generators

Ways to draw random numbers in Python:

1.  NumPy: [*new* programming interface](https://numpy.org/doc/stable/reference/random/generator.html) 
2.  NumPy: [*legacy* programming interface](https://numpy.org/doc/stable/reference/random/legacy.html) (don't use)
3.  Python standard library: [`random`](https://docs.python.org/3/library/random.html#random.random) module (don't use)

**A note on random number generation**

-   Random numbers drawn on a computer are almost never truly random
-   Sometimes referred to as *"pseudo"* random numbers

***
### Simple random data generation

-   Create RNG instance using [`default_rng()`](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.default_rng)


*Example: drawing random floating-point numbers from [0, 1)*

- Use [`random()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html)

In [1]:
from numpy.random import default_rng

# Get an instance of a RNG
rng = default_rng()
rng

Generator(PCG64) at 0x107D7CBA0

In [ ]:
# Generate 5 floats on the interval [0, 1) (includes 0, never 1)
numbers = rng.random(5)
numbers

array([0.74408105, 0.8923545 , 0.49364536, 0.82140558, 0.78228983])

*Example: drawing random floating-point numbers using same seed*

In [6]:
# Generate an RNG with an initial seed
seed = 123
rng = default_rng(123)


In [ ]:
numbers = rng.random(5)  # Seed updates everytime you run this, so the set seed of 123 in the previous cell only counts right afer running that cell.
numbers

array([0.68235186, 0.05382102, 0.22035987, 0.18437181, 0.1759059 ])

In [ ]:
rng = default_rng(123)  # Seed only counts for the first execution
for i in range(5):
    print(rng.random(5))

[0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]
[0.81209451 0.923345   0.2765744  0.81975456 0.88989269]
[0.51297046 0.2449646  0.8242416  0.21376296 0.74146705]
[0.6299402  0.92740726 0.23190819 0.79912513 0.51816504]
[0.23155562 0.16590399 0.49778897 0.58272464 0.18433799]


In [9]:
for i in range(5):
    rng = default_rng(123)  # Seed counts for every execution
    print(rng.random(5))

[0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]
[0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]
[0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]
[0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]
[0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]


*Example: drawing random integers*

- Use [`integers()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html)

In [ ]:
rng = default_rng(seed)

rng.integers(2, size=5)  # First argument is upper bound (non-inclusive)

array([0, 1, 1, 0, 1])

*Example: drawing higher-dimensional arrays*

- Use the `size=` argument to specify shape of resulting array

In [14]:
rng = default_rng(seed)
rng.integers(2, size=(5, 2))  # Matrix of random integers, size is a tuple

array([[0, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0]])

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>

Use the <tt>rng.random()</tt> function introduced above to draw a 5-by-2 matrix of random floating-point numbers which are uniformly distributed on the interval [-1, 1). Use a seed of 12345 for this exercise.
</div>
<span style="display: none;">YourTurnEnd</span>

In [10]:
rng = default_rng(12345)

unif = rng.random((5, 2))

# Rescale and shift onto [-1, 1)
unif * 2 - 1

array([[-0.54532796, -0.36648332],
       [ 0.59473091,  0.35250934],
       [-0.2177809 , -0.33437214],
       [ 0.19661751, -0.62653163],
       [ 0.34551209,  0.88360573]])

***
### Drawing random numbers from distributions

NumPy supports numerous distributions ([complete list](https://numpy.org/doc/stable/reference/random/generator.html#distributions)):

-   [`binomial()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.RandomState.binomial.html)
-   [`exponential()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.RandomState.exponential.html)
-   [`normal()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.RandomState.normal.html)
-   [`lognormal()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.RandomState.lognormal.html)
-   [`multivariate_normal()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.RandomState.multivariate_normal.html)
-   [`uniform()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.RandomState.uniform.html)
-   [`standard_t()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.standard_t.html)

*Example: Drawing from a normal distribution*

- Mean $\mu=1.0$, standard deviation $\sigma=0.5$

In [11]:
# Parameters of normal distribution
mu = 1.0
sigma = .5

# Get RNG instance
rng = default_rng(seed=123)

# Draw normally distributed random numbers
N = 5
rng.normal(mu, sigma, N)

array([0.50543932, 0.81610667, 1.64396263, 1.09698721, 1.46011545])

*Example: Drawing from a multivariate normal distribution*

-   Mean $\mathbf{\mu} = \begin{bmatrix} 0 \\ 1\end{bmatrix}$,
    variance-covariance matrix
$\mathbf{\Sigma} =\begin{bmatrix} \sigma_1^2 & \rho \sigma_1\sigma_2 \\ \rho\sigma_1\sigma_2 & \sigma_2^2\end{bmatrix}$
with $\sigma_1 = 0.5$, $\sigma_2 = 1.0$, and $\rho = 0.5$

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>

Use the <a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.RandomState.uniform.html"><tt>uniform()</tt></a> function from NumPy to draw a sample of 10 uniformly distributed
numbers on the interval [-1, 1]. Use a seed of 456 for this exercise.

</div>
<span style="display: none;">YourTurnEnd</span>

***
# Plotting with Matplotlib

- Matplotlib is the standard plotting library for Python
- Not part of core Python, needs to be installed (e.g., via Anaconda) and imported:

    ```python
    import matplotlib.pyplot as plt
    ```
- Higher-level alternative: [seaborn](https://seaborn.pydata.org/)

***
## Line plots

- Use [`plot()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html)

### Plotting single lines

*Example: plotting single line*

### Plotting multiple lines

#### Plot styles

*Main colors*
(see [here](https://matplotlib.org/stable/tutorials/colors/colors.html) for details,
    see [here](https://matplotlib.org/stable/gallery/color/named_colors.html#base-colors) for list of named colors):

- `b`: blue
- `g`: green
- `r`: red
- `c`: cyan
- `m`: magenta
- `y`: yellow
- `k`: black
- `w`: white

*Line styles:*

-   `-` solid line
-   `--` dashed line
-   `-.` dash-dotted line
-   `:` dotted line

*Marker styles ([complete list](https://matplotlib.org/stable/api/markers_api.html)):*

- `o`: circle
- `s`: square
- `*`: star
- `x`: x
- `d`: (thin) diamond

*Example: Multiple lines in single plot()*

*Example: Multiple plot() calls*

*Example: styling with keyword arguments*

-   See section on _Other Parameters_ in [`plot()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html)
-   Keyword arguments can be abbreviated:

    - `c` or `color`
    - `ls` or `linestyle`
    - `lw` or `linewidth`
    - `ms` or `markersize`

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>
Consider the standard CRRA utility function given by 
<i>u(c) = c<sup>1-γ</sup> / (1-γ)</i>.

Create a graph that shows the function over the interval [0.1, 2] with two lines for two distinct values of <i>γ</i>:
<ol>
    <li><i>γ = 1.1</i> using a blue dashed line with a line width of 0.5.</li>
    <li><i>γ = 2</i> using an orange line with line width of 0.75.</li>
</ol>
</div>
<span style="display: none;">YourTurnEnd</span>

***
## Scatter plots

- Use [`scatter()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html) 

*Example: Scatter y-values randomly drawn from [0, 1)*

In [ ]:
import numpy as np

# Number of points
N = 50

# Create 50 uniformly-spaced values on the unit interval
xvalues = np.linspace(0.0, 1.0, N)

*Example: Scatter with marker sizes randomly drawn from [0, 150)*

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>


Recall the example on how to draw a sample from a multivariate normal distribution 
covered in the previous section.

<ol>
    <li>Repeat the exercise, but now draw a sample of size 100.</li>
    <li>Visualize the first vs. the second dimension of this random sample as a scatter plot.</li>
</ol>
</div>
<span style="display: none;">YourTurnEnd</span>

***

## Histograms

- Use [`hist()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html)

*Example: Histogram of normal draws*

- Draw 100 points from a normal distribution and plot as a histogram

In [ ]:
from numpy.random import default_rng

# location and scale parameters of normal distribution
mu = 1.0
sigma = 0.5

# Get RNG instance
rng = default_rng(123)

***
## Plotting categorical data

- Create bar charts with [`bar()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.bar.html)

*Example: Population sizes by municipality*

- Municipalities: `'Oslo', 'Bergen', 'Trondheim', 'Stavanger'`
- Population: 717710, 291940, 214565, 149048

In [ ]:
import numpy as np

# Define category labels
municipality = ['Oslo', 'Bergen', 'Trondheim', 'Stavanger']
# Population in thousands
population = np.array([717710, 291940,  214565, 149048]) / 1000

*Example: Horizontal bar charts*

- Use [`barh()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.barh.html)

***
## Adding labels and annotations

-   Titles: [`title()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.title.html) 
    and [`suptitle()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.suptitle.html) 
-   Axes labels:
    [`xlabel()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.xlabel.html) 
    and [`ylabel()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ylabel.html)
-   Legend: 
    [`legend()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.legend.html)
-   Add text at arbitrary position: [`text()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.text.html)

In [ ]:
# Demo data used for plotting
xvalues = [0, 1, 2, 3]
yvalues = [1, 4, 2, 3]
yvalues2 = [2.0, 1.0, 3.0, 0.0]

***
## Plot limits, ticks and tick labels

-   Plot limits:
    [`xlim()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.xlim.html) and 
    [`ylim()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ylim.html)
-   Ticks and tick labels:
    [`xticks()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.xticks.html) 
    and [`yticks()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.yticks.html)


*Example: sine function plotted on $[0, 2\pi]$*

In [ ]:
import numpy as np

# Create data using the sine function
xvalues = np.linspace(0.0, 2*np.pi, 50)
yvalues = np.sin(xvalues)

# Define tick positions
xticks = [0.0, np.pi, 2*np.pi]
# Define tick labels (can use LaTeX code!)
xtick_labels = ['0', r'$\pi$', r'$2\pi$']

***

## Adding straight lines

- Horizontal lines: [`axhline()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.axhline.html)
- Vertical lines: [`axvline()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.axvline.html)
- Other: [`axline()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.axline.html#matplotlib.pyplot.axline)

*Example: Adding horizontal and vertical lines*

- Add horizontal line at 0, vertical lines at $\left[\frac{1}{2}\pi, \frac{3}{2}\pi\right]$ to previous sine function plot

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>

Plot the function <i>y=(x-1)<sup>2</sup></i> on the interval [0, 2]:
<ol>
    <li>Create a grid of 50 <i>x</i>-values using <a href="https://numpy.org/doc/stable/reference/generated/numpy.linspace.html"><tt>np.linspace()</tt></a>.</li>
    <li>Compute and plot the <i>y</i>-values.</li>
    <li>Label the <i>x</i>- and <i>y</i>-axes with <i>"x"</i> and <i>"y"</i>.</li>
    <li>Add the title <i>y = (x-1)<sup>2</sup></i>.</li>
    <li>Add a vertical line at <i>x=1</i> using a dashed line style.</li>
</ol>

</div>
<span style="display: none;">YourTurnEnd</span>

***
## Object-oriented interface

- Useful for figures with multiple sub-plots
- Cleaner interface
- Operate on instances of [`Figure`](https://matplotlib.org/stable/api/figure_api.html) 
    and [`Axes`](https://matplotlib.org/stable/api/axes_api.html) objects
- Objects are created with [`subplots()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplots.html) function:
    ```python
    fig, ax = plt.subplots()
    ```

### Example: annotations in pyplot vs. object-oriented interface

#### pyplot interface

-   This repeats the annotations example from above

In [ ]:
import matplotlib.pyplot as plt

# Demo data used for plotting
xvalues = [0, 1, 2, 3]
yvalues = [1, 4, 2, 3]
yvalues2 = [2.0, 1.0, 3.0, 0.0]

plt.plot(xvalues, yvalues, color='red')
plt.plot(xvalues, yvalues2, color='blue')

# Add titles, labels, legend, and text
plt.suptitle('Figure title')
plt.title('Axes-specific title')
plt.xlabel('Label for x-axis')
plt.ylabel('Label for y-axis')
plt.legend(['Red line', 'Blue line'])
# Adds text at data coordinates (0.05, 0.05)
plt.text(0.05, 0.05, 'More text')

#### Object-oriented interface

- Create the same plot using the object-oriented interface

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>

Recall the example from above in which we drew from a normal distribution and visualized the sample using a histogram.

<ol>
    <li>Repeat these steps, but create the histogram using the object-oriented Matplotlib interface.</li>
    <li>Set the x-axis label to 'Realized random number' and the y-axis label to 'Number of observations'.</li>
    <li>Add the title 'Histogram of normal draws'.</li>
</ol>

</div>
<span style="display: none;">YourTurnEnd</span>

***
## Working with multiple plots (axes)

- Use [`subplots()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplots.html) to obtain multiple sub-plots (axes)

*Example: Create a plot with 2 panels*

- Plot 1st and 2nd-degree polynomials

*Example: Create a figure with 2 rows and 2 columns*

- Plot polynomials of degrees 1 to 4
- Use `sharex` and `sharey` to enforce identical axes limits

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>
Create a figure with 3 columns (on a single row) and plot the following functions
on the interval [0, 6]:
<ol>
    <li>Subplot 1: <i>y = sin(x)</i></li>
    <li>Subplot 2: <i>y = sin(2*x)</i></li>
    <li>Subplot 3: <i>y = sin(4*x)</i></li>
</ol>

<i>Hint:</i> The sine function can be imported from NumPy as <TT>np.sin()</TT>.
</div>
<span style="display: none;">YourTurnEnd</span>

***
## Plotting with pandas

 - Pandas is a library to process and analyze data in Python (covered **later** in the course)
 - Pandas provides convenience functions for plotting
 - You can skip this section until we have covered pandas in part 3


### Bar charts

- Use pandas's [`plot.bar()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.bar.html):

*Example: Plot population of 15 largest municipalities in Norway*

In [ ]:
# Path to local data/ folder
DATA_PATH = '../../data'

# Path to CSV file
filepath = f'{DATA_PATH}/population_norway.csv'

*Example: Create bar chart in Matplotlib without pandas*

***
### Plotting time series data

- Use
[`DataFrame.plot()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.html) 

*Example: Plot US unemployment rate*

In [4]:
# Path to annual FRED data; DATA_PATH variable was defined above!
filepath = f'{DATA_PATH}/FRED/FRED_annual.csv'

***
### Scatter plots

- Use [`DataFrame.plot.scatter()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.scatter.html)

*Example: Plot inflation vs. unemployment rate*

In [5]:
# Path to annual FRED data; DATA_PATH variable was defined above!
filepath = f'{DATA_PATH}/FRED/FRED_annual.csv'

*Example: Multiple scatter plots*

- Use [`scatter_matrix()`](https://pandas.pydata.org/docs/reference/api/pandas.plotting.scatter_matrix.html)


*Example: plot unemployment rate vs. inflation vs. Fed Funds Rate*

In [7]:
from pandas.plotting import scatter_matrix

***
### Box plots

- Use
[`DataFrame.plot.box()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.box.html)
- Shows median, interquartile range (25th to 75th percentile) and outliers

*Example: Unemployment rate, inflation, and Fed Funds Rate*

In [6]:
# Path to annual FRED data; DATA_PATH variable was defined above!
filepath = f'{DATA_PATH}/FRED/FRED_annual.csv'